### ISSUE TITLE
Doesn't shut off properly after it's done, under static LED modes

### ISSUE THREAD

**Issue by cdisselkoen** [keyboardio/Kaleidoscope-LEDEffect-BootGreeting#5]
Reference: https://community.keyboard.io/t/led-key-keeps-glowing-when-the-keyboard-is-plugged-in/697/3 (about the third post and following)

The correct fix is `LEDControl.refreshAt()`, I think.

**Comment by cdisselkoen** [comment]
Edit: I now see #3, so either this was already fixed and the bug reports in the linked thread are on old versions, or the fix in #3 was insufficient

**Comment by algernon** [comment]
I believe this to be fixed now. If it still persists, after updating the involved plugins, please reopen.
